parse_config:
  raw_binding_map:
    '&sys_reset': Reset
    '&bootloader': Boot
    '&caps_word': Caps Word

  zmk_keycode_map:
    # Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    C_PLAY_PAUSE: "▷||"
    ESCAPE: "ESC"
    COMMA: ","
    DOT: "."
    DOUBLE_QUOTES: '"'
    SQT: "'"
    SLASH: "/"
    MINUS: "-"
    GRAVE: "`"
    LEFT_BRACKET: "["
    RIGHT_BRACKET: "]"
    LEFT_BRACE: "{"
    RIGHT_BRACE: "}"
    BACKSLASH: "\\"
    AT_SIGN: "@"
    LANGUAGE_1: "かな"
    LANGUAGE_2: "英数"

draw_config:
  dark_mode: auto
  glyph_tap_size: 18
  footer_text: 'hmkb44 KEYMAPS | Created with keymap-drawer' 